feat: infinite wait for the next key after `-`,`=`
NeogitOrg/neogit pull request #748
Opened 2023-08-14 11:19 UTC by IndianBoy42

Register a handler for every prefix that blocks waiting for the next key
using `getcharstr` and invokes the correct mapping

2023-08-14 11:21 UTC, IndianBoy42 commented
Limitations: assumes that these arg/opt mappings are only 2 characters: the prefix and then some char. Handling more general cases gets pretty complicated. Need to get all partial prefixes, construct some kind of tree, check on every char if we are at a leaf/branch or else continue/break. Basically everything that which-key.nvim does

2023-08-14 11:24 UTC, CKolkey commented
Does this handle `as` and `ar` (the bottom two) on the branch config popup? (`bC<cr>`)

2023-08-14 11:30 UTC, IndianBoy42 commented
I think it is less necessary for `as/ar` since those are both just simple lower case characters. The args and opts cases required quick pressing and unpressing of shift which made it quite awkward (worse for me specifically since symbols are under a layer in my split keyboard)

2023-08-15 16:20 UTC, CKolkey requested changes

2023-08-15 16:20 UTC, CKolkey commented on lua/neogit/lib/popup/init.lua
> +  -- TODO:
Whats the todo? :)

2023-08-22 13:13 UTC, IndianBoy42 commented on lua/neogit/lib/popup/init.lua
> +      table.insert(arg_prefixes, arg.key_prefix)
There is an even better way: we can use `table[key_prefix] = true` to effectively make a hashset of the prefixes

2023-08-22 13:34 UTC, CKolkey commented
Agreed. Thanks for the contribution - I didn't know about `getchrstring()`

2023-08-22 13:34 UTC, merged