FIX: Properly render HEAD with `NeogitBranchHead` highlight group
NeogitOrg/neogit pull request #974
Opened 2023-11-27 10:59 UTC by gollth

Sorry I just noticed, I introduced a small bug in my previous PR #934, where local checked out branches are not rendered with the `NeogitBranchHead`. With a user config of:

```lua
local blue = "#bae7ff"
local remote = "#b4eeb2"

vim.api.nvim_set_hl(0, "NeogitBranch", { fg = blue, bold = true })
vim.api.nvim_set_hl(0, "NeogitBranchHead", { fg = blue, bold = true, underline = true })
vim.api.nvim_set_hl(0, "NeogitRemote", { fg = remote, italic = true })
```

and a branch called `foo` checked out, this is what happens:

|Before|After|
|:--|:--|
|![before](https://github.com/NeogitOrg/neogit/assets/31999281/268f9c5d-71da-424c-a5f1-520230c04581)|![after](https://github.com/NeogitOrg/neogit/assets/31999281/7268f654-c7cf-4a7b-bb15-644a2f2c6a97)|

This PR should fix this now =)

2023-11-27 11:50 UTC, CKolkey requested changes
Looks great, lets just remove the commented out line and we're good :)

2023-11-27 11:50 UTC, CKolkey commented on lua/neogit/buffers/common.lua
> +    -- print(">> " .. vim.inspect(commit.ref_name) .. " (" .. vim.inspect(is_head) .. "): " .. vim.inspect(info))
Probably can remove this?

2023-11-28 07:45 UTC, gollth commented
Dammit I noticed another bug, while retesting this... 

Right now there is now way to display _remote only_ branches. My impl will always highlight the last part of each branch with the `NeogitBranch` highlight group:

| Before | After |
|:--|:--|
|![before](https://github.com/NeogitOrg/neogit/assets/31999281/b3854dc5-d1ea-473d-8d8f-823afccccb78)|![after](https://github.com/NeogitOrg/neogit/assets/31999281/0847a2eb-c378-4170-becd-2383aeb7889c)|

Note in the example above, how `github/master` and `gollth/master` are both highlighted in green/blue indicating that my local `master` branch is both at `github/master` & `gollth/master` AT THE SAME TIME !?! Same goes with with the `fix-head-log-graph` being locally a commit further than its remote AND SIMULTANEOUSLY at its remote...

This should be fixed now as well, sorry for all the confusion @CKolkey. Git is hard... 🙈

2023-11-28 08:11 UTC, CKolkey commented
Haha, no joke. The last 10~ months of working on this project have been a great deep-dive into _so much_ of how git works under the hood, and I still feel like I know almost nothing. So many small details.

2023-11-28 15:46 UTC, gollth commented
I can imagine o.O This Torvalds dude is quite the smart guy

2023-11-28 18:18 UTC, CKolkey commented
No joke. Once (linux) is good luck. Twice (git)... impressive. I watched a talk he gave at google in like... 2010 maybe, the very early days of git. Very interesting to see him explain the shortcomings of every other VCS available, things that I definitely take for granted like "easy branching" and "fully decentralised". Good stuff.

2023-11-28 20:17 UTC, merged